import os

dirs = [
    'src/components/layout',
    'src/components/ui',
    'src/components/sections',
    'src/components/products',
    'src/lib/mock-data',
    'src/lib/utils'
]

for d in dirs:
    os.makedirs(d, exist_ok=True)

files = {
    'src/lib/utils.ts': '''import { clsx, type ClassValue } from "clsx"\\nimport { twMerge } from "tailwind-merge"\\n\\nexport function cn(...inputs: ClassValue[]) {\\n  return twMerge(clsx(inputs))\\n}\\n''',
    
    'src/components/ui/Button.tsx': '''import * as React from "react"\\nimport { cn } from "@/lib/utils"\\n\\nexport interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\\n  variant?: "primary" | "secondary" | "text" | "outline"\\n}\\n\\nconst Button = React.forwardRef<HTMLButtonElement, ButtonProps>(\\n  ({ className, variant = "primary", ...props }, ref) => {\\n    const baseStyles = "inline-flex items-center justify-center whitespace-nowrap rounded-sm text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-brand-navy disabled:pointer-events-none disabled:opacity-50"\\n    const variants = {\\n      primary: "bg-brand-navy text-white hover:bg-brand-navy/90",\\n      secondary: "bg-brand-gold text-brand-navy hover:bg-brand-gold/90",\\n      outline: "border border-brand-navy bg-transparent text-brand-navy hover:bg-brand-navy hover:text-white",\\n      text: "text-brand-navy underline-offset-4 hover:underline"\\n    }\\n    return (\\n      <button\\n        className={cn(baseStyles, variants[variant], "h-10 px-6 py-2", className)}\\n        ref={ref}\\n        {...props}\\n      />\\n    )\\n  }\\n)\\nButton.displayName = "Button"\\n\\nexport { Button }\\n''',

    'src/components/ui/Card.tsx': '''import * as React from "react"\\nimport { cn } from "@/lib/utils"\\n\\nconst Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(\\n  ({ className, ...props }, ref) => (\\n    <div\\n      ref={ref}\\n      className={cn("rounded-lg border border-brand-navy/10 bg-white text-brand-charcoal shadow-sm", className)}\\n      {...props}\\n    />\\n  )\\n)\\nCard.displayName = "Card"\\n\\nexport { Card }\\n''',

    'src/components/ui/BentoGrid.tsx': '''import * as React from "react"\\nimport { cn } from "@/lib/utils"\\n\\nexport const BentoGrid = ({ className, children }: { className?: string, children?: React.ReactNode }) => {\\n  return (\\n    <div className={cn("grid md:auto-rows-[18rem] grid-cols-1 md:grid-cols-3 gap-4 max-w-7xl mx-auto", className)}>\\n      {children}\\n    </div>\\n  )\\n}\\n\\nexport const BentoGridItem = ({\\n  className, title, description, header, icon\\n}: {\\n  className?: string, title?: string | React.ReactNode, description?: string | React.ReactNode, header?: React.ReactNode, icon?: React.ReactNode\\n}) => {\\n  return (\\n    <div className={cn("row-span-1 rounded-xl group/bento hover:shadow-xl transition duration-200 shadow-input dark:shadow-none p-4 dark:bg-black dark:border-white/[0.2] bg-white border border-transparent justify-between flex flex-col space-y-4", className)}>\\n      {header}\\n      <div className="group-hover/bento:translate-x-2 transition duration-200">\\n        {icon}\\n        <div className="font-sans font-bold text-brand-navy mb-2 mt-2">{title}</div>\\n        <div className="font-sans font-normal text-brand-charcoal text-xs">{description}</div>\\n      </div>\\n    </div>\\n  )\\n}\\n''',

    'src/components/layout/SiteHeader.tsx': '''import Link from "next/link"\\nimport { Button } from "@/components/ui/Button"\\nimport Image from "next/image"\\n\\nexport function SiteHeader() {\\n  return (\\n    <header className="sticky top-0 z-50 w-full border-b border-brand-navy/10 bg-brand-ivory/80 backdrop-blur-md">\\n      <div className="container mx-auto px-4 h-20 flex items-center justify-between">\\n        <Link href="/" className="flex items-center gap-2">\\n          <Image src="/assets/perlinternationallogo.svg" alt="Pearl International" width={180} height={60} className="h-10 w-auto" />\\n        </Link>\\n        <nav className="hidden md:flex gap-8">\\n          <Link href="/" className="text-sm font-medium text-brand-charcoal hover:text-brand-gold transition-colors">Home</Link>\\n          <Link href="#about" className="text-sm font-medium text-brand-charcoal hover:text-brand-gold transition-colors">About Us</Link>\\n          <Link href="#products" className="text-sm font-medium text-brand-charcoal hover:text-brand-gold transition-colors">Products</Link>\\n          <Link href="#quality" className="text-sm font-medium text-brand-charcoal hover:text-brand-gold transition-colors">Quality</Link>\\n          <Link href="#contact" className="text-sm font-medium text-brand-charcoal hover:text-brand-gold transition-colors">Contact Us</Link>\\n        </nav>\\n        <div className="flex items-center gap-4">\\n          <Button className="hidden md:inline-flex">Enquire Now</Button>\\n          <button className="md:hidden">Menu</button>\\n        </div>\\n      </div>\\n    </header>\\n  )\\n}\\n''',

    'src/components/layout/SiteFooter.tsx': '''import Link from "next/link"\\nimport Image from "next/image"\\n\\nexport function SiteFooter() {\\n  return (\\n    <footer className="bg-brand-navy text-white py-16">\\n      <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-4 gap-8">\\n        <div className="space-y-4">\\n          <Image src="/assets/perlinternationallogo.svg" alt="Pearl International" width={180} height={60} className="h-10 w-auto brightness-0 invert" />\\n          <p className="text-brand-ivory/80 text-sm">Premium agricultural export partner delivering quality globally.</p>\\n        </div>\\n        <div>\\n          <h4 className="font-serif font-bold text-brand-gold mb-4 text-xl">Quick Links</h4>\\n          <ul className="space-y-2 text-sm text-brand-ivory/80">\\n            <li><Link href="/">Home</Link></li>\\n            <li><Link href="#about">About Us</Link></li>\\n            <li><Link href="#products">Products</Link></li>\\n          </ul>\\n        </div>\\n        <div>\\n          <h4 className="font-serif font-bold text-brand-gold mb-4 text-xl">Products</h4>\\n          <ul className="space-y-2 text-sm text-brand-ivory/80">\\n            <li><Link href="#products">Coconuts</Link></li>\\n            <li><Link href="#products">Spices</Link></li>\\n            <li><Link href="#products">Vegetables</Link></li>\\n          </ul>\\n        </div>\\n        <div>\\n          <h4 className="font-serif font-bold text-brand-gold mb-4 text-xl">Contact</h4>\\n          <ul className="space-y-2 text-sm text-brand-ivory/80">\\n            <li>Email: info@pearlinternational.com</li>\\n            <li>Phone: +1 234 567 890</li>\\n          </ul>\\n        </div>\\n      </div>\\n      <div className="container mx-auto px-4 mt-12 pt-8 border-t border-white/10 text-center text-sm text-brand-ivory/60">\\n        <p>&copy; {new Date().getFullYear()} Pearl International. All rights reserved.</p>\\n      </div>\\n    </footer>\\n  )\\n}\\n''',

    'src/lib/mock-data/categories.ts': '''export const mockCategories = [\\n  { id: "1", name: "Coconuts", slug: "coconuts", description: "Premium quality coconuts from the best farms." },\\n  { id: "2", name: "Spices", slug: "spices", description: "Aromatic and authentic spices." },\\n  { id: "3", name: "Vegetables", slug: "vegetables", description: "Fresh and organic vegetables." },\\n]\\n''',

    'src/lib/mock-data/products.ts': '''export const mockProducts = [\\n  { id: "1", category_id: "1", name: "Coconut", slug: "coconut" },\\n  { id: "2", category_id: "1", name: "Tender Coconut", slug: "tender-coconut" },\\n  { id: "3", category_id: "1", name: "Cocoa Peat", slug: "cocoa-peat" },\\n  { id: "4", category_id: "2", name: "Cardamom", slug: "cardamom" },\\n  { id: "5", category_id: "2", name: "Black Pepper", slug: "black-pepper" },\\n  { id: "6", category_id: "3", name: "Onions", slug: "onions" },\\n  { id: "7", category_id: "3", name: "Small Onions", slug: "small-onions" },\\n]\\n''',
}

for path, content in files.items():
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
