import os

components = {
    'src/components/ui/PageHero.tsx': '''import Image from "next/image"\\n\\ninterface PageHeroProps {\\n  title: string\\n  description?: string\\n  imageSrc: string\\n}\\n\\nexport function PageHero({ title, description, imageSrc }: PageHeroProps) {\\n  return (\\n    <section className="relative h-[40vh] min-h-[350px] max-h-[600px] flex items-center bg-brand-navy overflow-hidden">\\n      <div className="absolute inset-0 z-0 opacity-40">\\n        <div className="w-full h-full bg-gradient-to-t from-brand-navy via-brand-navy/60 to-transparent absolute z-10" />\\n        <Image \\n          src={imageSrc} \\n          alt="" \\n          fill \\n          sizes="100vw"\\n          className="object-cover grayscale mix-blend-overlay"\\n          priority\\n        />\\n      </div>\\n      <div className="container mx-auto px-4 z-10 text-center space-y-4 md:space-y-6">\\n        <h1 className="text-3xl md:text-5xl lg:text-6xl font-serif text-white max-w-4xl mx-auto balance-text">\\n          {title}\\n        </h1>\\n        {description && (\\n          <p className="text-lg md:text-xl text-brand-ivory/80 max-w-2xl mx-auto font-sans">\\n            {description}\\n          </p>\\n        )}\\n      </div>\\n    </section>\\n  )\\n}\\n''',

    'src/components/ui/FAQ.tsx': '''"use client"\\nimport * as React from "react"\\nimport { cn } from "@/lib/utils"\\nimport { ChevronDown } from "lucide-react"\\n\\nexport function FAQ({ items }: { items: { question: string, answer: string }[] }) {\\n  const [openIndex, setOpenIndex] = React.useState<number | null>(null)\\n  \\n  return (\\n    <div className="space-y-4 w-full" role="region" aria-label="Frequently Asked Questions">\\n      {items.map((item, i) => (\\n        <div key={i} className="border border-brand-navy/10 rounded-xl overflow-hidden bg-white shadow-sm">\\n          <button \\n            className="w-full px-6 py-5 flex items-center justify-between text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold transition-colors hover:bg-brand-navy/5"\\n            onClick={() => setOpenIndex(openIndex === i ? null : i)}\\n            aria-expanded={openIndex === i}\\n            aria-controls={aq-answer-}\\n            id={aq-question-}\\n          >\\n            <span className="font-serif font-bold text-brand-navy text-lg pr-4">{item.question}</span>\\n            <ChevronDown \\n              className={cn("w-5 h-5 text-brand-gold transition-transform duration-300 shrink-0 motion-reduce:transition-none", openIndex === i && "rotate-180")} \\n              aria-hidden="true"\\n            />\\n          </button>\\n          <div \\n            id={aq-answer-}\\n            role="region"\\n            aria-labelledby={aq-question-}\\n            className={cn("overflow-hidden transition-all duration-300 motion-reduce:transition-none", openIndex === i ? "max-h-[500px] opacity-100" : "max-h-0 opacity-0")}\\n          >\\n            <p className="text-brand-charcoal/80 font-sans px-6 pb-5 pt-1">{item.answer}</p>\\n          </div>\\n        </div>\\n      ))}\\n    </div>\\n  )\\n}\\n''',

    'src/components/ui/Breadcrumbs.tsx': '''import Link from "next/link"\\nimport { ChevronRight, Home } from "lucide-react"\\n\\ninterface BreadcrumbItem {\\n  label: string\\n  href: string\\n}\\n\\nexport function Breadcrumbs({ items }: { items: BreadcrumbItem[] }) {\\n  return (\\n    <nav aria-label="Breadcrumb" className="py-4 overflow-x-auto">\\n      <ol className="flex items-center space-x-2 text-sm text-brand-charcoal/60 whitespace-nowrap">\\n        <li>\\n          <Link \\n            href="/" \\n            className="flex items-center hover:text-brand-navy transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold rounded-sm"\\n            aria-label="Home"\\n          >\\n            <Home className="w-4 h-4" />\\n          </Link>\\n        </li>\\n        {items.map((item, index) => (\\n          <li key={index} className="flex items-center space-x-2">\\n            <ChevronRight className="w-4 h-4 text-brand-navy/30 shrink-0" aria-hidden="true" />\\n            {index === items.length - 1 ? (\\n              <span className="text-brand-navy font-medium truncate max-w-[200px] sm:max-w-none" aria-current="page">\\n                {item.label}\\n              </span>\\n            ) : (\\n              <Link \\n                href={item.href} \\n                className="hover:text-brand-navy transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold rounded-sm truncate max-w-[150px] sm:max-w-none"\\n              >\\n                {item.label}\\n              </Link>\\n            )}\\\n          </li>\\n        ))}\\n      </ol>\\n    </nav>\\n  )\\n}\\n''',

    'src/components/ui/EmptyState.tsx': '''import { SearchX } from "lucide-react"\\nimport { Button } from "./Button"\\nimport Link from "next/link"\\n\\ninterface EmptyStateProps {\\n  title: string\\n  description: string\\n  actionLabel?: string\\n  actionHref?: string\\n}\\n\\nexport function EmptyState({ title, description, actionLabel, actionHref }: EmptyStateProps) {\\n  return (\\n    <div className="flex flex-col items-center justify-center py-16 px-4 text-center border-2 border-dashed border-brand-navy/10 rounded-2xl bg-brand-navy/5">\\n      <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mb-6 shadow-sm">\\n        <SearchX className="w-8 h-8 text-brand-navy/40" aria-hidden="true" />\\n      </div>\\n      <h3 className="font-serif text-2xl text-brand-navy mb-2">{title}</h3>\\n      <p className="text-brand-charcoal/60 font-sans max-w-md mb-8">{description}</p>\\n      {actionLabel && actionHref && (\\n        <Link href={actionHref}>\\n          <Button variant="outline">{actionLabel}</Button>\\n        </Link>\\n      )}\\n    </div>\\n  )\\n}\\n''',
    
    'src/components/ui/ProductSkeleton.tsx': '''export function ProductSkeleton() {\\n  return (\\n    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">\\n      {[1, 2, 3].map((i) => (\\n        <div key={i} className="rounded-2xl overflow-hidden border border-brand-navy/10 bg-white shadow-sm flex flex-col animate-pulse">\\n          <div className="h-64 bg-brand-navy/5 w-full"></div>\\n          <div className="p-6 flex flex-col flex-1 space-y-4">\\n            <div className="h-6 bg-brand-navy/10 rounded w-3/4"></div>\\n            <div className="space-y-2">\\n              <div className="h-4 bg-brand-navy/5 rounded"></div>\\n              <div className="h-4 bg-brand-navy/5 rounded w-5/6"></div>\\n            </div>\\n            <div className="mt-auto pt-6 space-y-3">\\n              <div className="h-10 bg-brand-navy/10 rounded-lg w-full"></div>\\n              <div className="h-10 bg-brand-navy/10 rounded-lg w-full"></div>\\n            </div>\\n          </div>\\n        </div>\\n      ))}\\n    </div>\\n  )\\n}\\n''',
}

for path, content in components.items():
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
